In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('../bus_stop/data/stops-manhattan.txt')

In [7]:
df

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station
0,400001,4 AV/E 9 ST,NaN,40.730640,-73.990440,NaN,NaN,0,NaN
1,400002,4 AV/E 12 ST,NaN,40.732609,-73.989960,NaN,NaN,0,NaN
2,400003,4 AV/E 13 ST,NaN,40.733936,-73.989723,NaN,NaN,0,NaN
3,400007,PARK AV S/E 21 ST,NaN,40.738976,-73.987053,NaN,NaN,0,NaN
4,400026,MADISON AV/E 63 ST,NaN,40.766273,-73.969330,NaN,NaN,0,NaN
5,400027,MADISON AV/E 65 ST,NaN,40.767582,-73.968376,NaN,NaN,0,NaN
6,400028,MADISON AV/E 67 ST,NaN,40.768814,-73.967484,NaN,NaN,0,NaN
7,400029,MADISON AV/E 69 ST,NaN,40.770077,-73.966560,NaN,NaN,0,NaN
8,400030,MADISON AV/E 72 ST,NaN,40.772148,-73.965050,NaN,NaN,0,NaN
9,400032,MADISON AV/E 77 ST,NaN,40.775322,-73.962738,NaN,NaN,0,NaN
10,400033,MADISON AV/E 79 ST,NaN,40.776695,-73.961731,NaN,NaN,0,NaN
11,400034,MADISON AV/E 83 ST,NaN,40.778793,-73.960205,NaN,NaN,0,NaN
12,400036,MADISON AV/E 86 ST,NaN,40.781155,-73.958481,NaN,NaN,0,NaN
13,400037,MADISON AV/E 89 ST,NaN,40.782677,-73.957375,NaN,NaN,0,NaN
14,400038,MADISON AV/E 91 ST,NaN,40.784359,-73.956139,NaN,NaN,0,NaN
15,400039,MADISON AV/E 93 ST,NaN,40.785637,-73.955208,NaN,NaN,0,NaN
16,400041,MADISON AV/E 98 ST,NaN,40.788414,-73.953178,NaN,NaN,0,NaN
17,400042,MADISON AV/E 101 ST,NaN,40.790302,-73.951797,NaN,NaN,0,NaN
18,400043,MADISON AV/E 102 ST,NaN,40.791370,-73.951019,NaN,NaN,0,NaN
19,400044,MADISON AV/E 104 ST,NaN,40.792160,-73.950447,NaN,NaN,0,NaN
20,400045,MADISON AV/E 106 ST,NaN,40.793434,-73.949509,NaN,NaN,0,NaN
21,400046,MADISON AV/E 107 ST,NaN,40.794552,-73.948692,NaN,NaN,0,NaN
22,400047,MADISON AV/E 109 ST,NaN,40.795815,-73.947777,NaN,NaN,0,NaN
23,400048,MADISON AV/E 111 ST,NaN,40.797024,-73.946892,NaN,NaN,0,NaN
24,400050,MADISON AV/E 115 ST,NaN,40.799541,-73.945053,NaN,NaN,0,NaN
25,400051,MADISON AV/E 118 ST,NaN,40.801506,-73.943619,NaN,NaN,0,NaN
26,400053,MADISON AV/E 123 ST,NaN,40.804779,-73.941330,NaN,NaN,0,NaN
27,400054,MADISON AV/E 125 ST,NaN,40.806015,-73.940346,NaN,NaN,0,NaN
28,400055,MADISON AV/E 127 ST,NaN,40.807247,-73.939461,NaN,NaN,0,NaN
29,400056,MADISON AV/E 129 ST,NaN,40.808510,-73.938538,NaN,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...
1813,903198,12 AV/W 40 ST,NaN,40.760822,-74.002052,NaN,NaN,0,NaN
1814,903199,12 AV/W 33 ST,NaN,40.756462,-74.005226,NaN,NaN,0,NaN
1815,903200,12 AV/W 30 ST,NaN,40.754898,-74.006348,NaN,NaN,0,NaN
1816,903206,12 AV/W 56 ST,NaN,40.771137,-73.993965,NaN,NaN,0,NaN
1817,903207,11 AV/W 42 ST,NaN,40.760662,-73.998535,NaN,NaN,0,NaN
1818,903209,Columbus Circle (does not stop),NaN,40.768242,-73.981293,NaN,NaN,0,NaN
1819,903210,RIVERBANK ST PARK/BAY 1,NaN,40.826756,-73.955421,NaN,NaN,0,NaN
1820,903214,12 AV/W 52 ST,NaN,40.768124,-73.995697,NaN,NaN,0,NaN
1821,903217,7 AV/W 36 ST,NaN,40.752411,-73.989731,NaN,NaN,0,NaN
1822,903218,W 72 ST/AMSTERDAM AV (M5 - does not stop),NaN,40.778713,-73.981766,NaN,NaN,0,NaN
1823,903219,FT GEORGE AV/66 FT GEORGE AV,NaN,40.858093,-73.925537,NaN,NaN,0,NaN
1824,903226,1 AV/E 20 ST (M23 non-stop),NaN,40.735352,-73.979568,NaN,NaN,0,NaN
1825,903228,CPW/110ST (not used),NaN,40.800831,-73.958328,NaN,NaN,0,NaN
1826,903229,BROADWAY/W 131 ST,NaN,40.817280,-73.956909,NaN,NaN,0,NaN
1827,903230,BROADWAY/W 133 ST,NaN,40.818443,-73.956512,NaN,NaN,0,NaN
1828,903231,W 178 ST/BROADWAY (M5 last stop),NaN,40.848263,-73.937454,NaN,NaN,0,NaN
1829,903232,10 AV/W15 (does not stop),NaN,40.743057,-74.008064,NaN,NaN,0,NaN
1830,903233,COL CIR (Time Warner) does not stop,NaN,40.768059,-73.982529,NaN,NaN,0,NaN
1831,903234,W 58 ST/BROADWAY (does not stop),NaN,40.767494,-73.981750,NaN,NaN,0,NaN
1832,903235,W 37 ST/BROADWAY,NaN,40.752178,-73.987389,NaN,NaN,0,NaN
1833,903236,BROADWAY / W 135 ST,NaN,40.820644,-73.954491,NaN,NaN,0,NaN
1834,903237,11 AV / W 17 ST,NaN,40.744415,-74.008148,NaN,NaN,0,NaN
1835,904046,lga/circle,NaN,40.770741,-73.867920,NaN,NaN,0,NaN
1836,904077,T7/T7,NaN,40.768147,-73.884750,NaN,NaN,0,NaN
1837,904167,Ditmars bl/100 st,NaN,40.770580,-73.871040,NaN,NaN,0,NaN
1838,904199,LGA/TERMINAL D(Drop off only),NaN,40.768074,-73.862091,NaN,NaN,0,NaN
1839,904200,LGA M60 E.B. (does not stop),NaN,40.767445,-73.863449,NaN,NaN,0,NaN
1840,904201,LGA-SBS60 W.B. (does not stop),NaN,40.769554,-73.881950,NaN,NaN,0,NaN
1841,904918,EAST 92 ST/YORK AV,NaN,40.779842,-73.944809,NaN,NaN,0,NaN
1842,904920,PIKE ST/CHERRY ST,NaN,40.710823,-73.991920,NaN,NaN,0,NaN